#include "GarageSystem.h"
#include <algorithm>
#include <cmath>
static float clamp01(float v){return v<0?0:(v>1?1:v);}
bool GarageSystem::addGarage(const GarageRecord& g){if(g.slots<1)return false;int max=(g.kind==GarageKind::Business)?100:50;if(g.slots>max)return false;for(const auto&x:garages_)if(x.id==g.id)return false;garages_.push_back(g);return true;}
int GarageSystem::usedSlots(const std::string&id)const{int n=0;for(const auto&v:vehicles_)if(v.garageId==id)++n;return n;}
int GarageSystem::capacity(const std::string&id)const{for(const auto&g:garages_)if(g.id==id&&g.owned)return g.slots;return 0;}
bool GarageSystem::addVehicle(const VehicleRecord&v){if(capacity(v.garageId)<=usedSlots(v.garageId))return false;for(const auto&x:vehicles_)if(x.id==v.id)return false;vehicles_.push_back(v);return true;}
bool GarageSystem::moveVehicle(const std::string&vid,const std::string&gid){if(capacity(gid)<=usedSlots(gid))return false;for(auto&v:vehicles_)if(v.id==vid){v.garageId=gid;return true;}return false;}
bool GarageSystem::setActiveVehicle(const std::string&id){bool found=false;for(auto&v:vehicles_){if(v.id==id){found=true;v.active=true;}else v.active=false;}return found;}
bool GarageSystem::setGetawayVehicle(const std::string&id,bool locked){for(auto&v:vehicles_)if(v.id==id){if(locked&&!v.heistCompatible)return false;v.getawayLocked=locked;return true;}return false;}
bool GarageSystem::repaint(const std::string&id,const std::string&p,const std::string&s,const std::string&w,PaintFinish f,int&bank,int&cost){for(auto&v:vehicles_)if(v.id==id){cost=(f==PaintFinish::Metallic?1800:(f==PaintFinish::Matte?1500:1200));if(bank<cost)return false;bank-=cost;v.custom.primary=p;v.custom.secondary=s;v.custom.wheel=w;v.custom.finish=f;return true;}return false;}
bool GarageSystem::restoreOriginalPaint(const std::string&id,int&bank,int&cost){for(auto&v:vehicles_)if(v.id==id){cost=750;if(bank<cost)return false;bank-=cost;v.custom.primary=v.custom.originalPrimary;v.custom.secondary=v.custom.originalSecondary;v.custom.finish=PaintFinish::Gloss;return true;}return false;}
bool GarageSystem::setTireSmokeColor(const std::string&id,const std::string&color,int&bank,int&cost){for(auto&v:vehicles_)if(v.id==id){cost=900;if(bank<cost)return false;bank-=cost;v.custom.tireSmoke=color;return true;}return false;}
bool GarageSystem::upgrade(const std::string&id,const std::string&part,int level,int&bank,int&cost){if(level<0||level>3)return false;for(auto&v:vehicles_)if(v.id==id){int*slot=nullptr;if(part=="engine")slot=&v.custom.engine;else if(part=="brakes")slot=&v.custom.brakes;else if(part=="transmission")slot=&v.custom.transmission;else if(part=="suspension")slot=&v.custom.suspension;else if(part=="tires")slot=&v.custom.tires;else if(part=="rims")slot=&v.custom.rims;else if(part=="lights")slot=&v.custom.lights;else if(part=="cosmetic")slot=&v.custom.cosmetic;else return false;if(level<=*slot){cost=0;return true;}cost=(level-*slot)*2500;if(bank<cost)return false;bank-=cost;*slot=level;return true;}return false;}
bool GarageSystem::setMissionLocked(const std::string&id,bool l){for(auto&v:vehicles_)if(v.id==id){v.missionLocked=l;return true;}return false;}
bool GarageSystem::damageVehicle(const std::string&id,float d){if(d<=0)return false;for(auto&v:vehicles_)if(v.id==id){v.condition=clamp01(v.condition-d);v.permanentWear=clamp01(v.permanentWear+d*0.18f);return true;}return false;}
bool GarageSystem::repairVehicle(const std::string&id,int&bank,int&cost){for(auto&v:vehicles_)if(v.id==id){float missing=1.0f-v.condition;if(missing<=0.001f){cost=0;return true;}cost=(int)std::ceil(v.purchasePrice*missing*0.22f);if(bank<cost)return false;bank-=cost;v.condition=1.0f;v.permanentWear=clamp01(v.permanentWear+missing*0.03f);return true;}return false;}
int GarageSystem::saleValue(const VehicleRecord&v)const{float base=0.80f;float damageFactor=0.35f+0.65f*clamp01(v.condition);float wearFactor=1.0f-0.22f*clamp01(v.permanentWear);float ratio=base*damageFactor*wearFactor;if(ratio>0.80f)ratio=0.80f;if(ratio<0.10f)ratio=0.10f;return (int)std::floor(v.purchasePrice*ratio);}
bool GarageSystem::sellVehicle(const std::string&id,int&bank,int&credit){for(auto it=vehicles_.begin();it!=vehicles_.end();++it)if(it->id==id){if(it->missionLocked||it->getawayLocked)return false;credit=saleValue(*it);bank+=credit;vehicles_.erase(it);return true;}return false;}
bool GarageSystem::transferBusinessVehicles(const std::string&type,const std::string&gid){int free=capacity(gid)-usedSlots(gid);if(free<0)return false;int need=0;for(const auto&v:vehicles_)if(v.businessVehicle&&v.businessType==type&&v.garageId!=gid)++need;if(need>free)return false;for(auto&v:vehicles_)if(v.businessVehicle&&v.businessType==type)v.garageId=gid;return true;}
std::vector<OwnedVehicle> GarageSystem::phoneVehicles()const{std::vector<OwnedVehicle>o;for(const auto&v:vehicles_)o.push_back({v.id,v.name,v.heistCompatible,v.businessVehicle,v.missionLocked});return o;}
