#include "game/Properties.h"
#include <cstdio>
PropertySystem::PropertySystem(){properties={{1,PropertyType::Apartment,{450,0,320},85000,false,1,true,false},{2,PropertyType::Apartment,{-700,0,520},125000,false,2,true,false},{3,PropertyType::House,{5400,0,1800},220000,false,4,true,false},{4,PropertyType::Villa,{-8200,0,4600},650000,false,10,true,false},{5,PropertyType::Penthouse,{900,0,-500},1200000,false,12,true,false},{6,PropertyType::BeachHouse,{42000,0,-35000},900000,false,16,true,false},{7,PropertyType::Mansion,{-15000,0,19000},3500000,false,50,true,false},{101,PropertyType::StandaloneGarage,{-3200,0,1200},45000,false,10,true,false},{102,PropertyType::StandaloneGarage,{17000,0,-9000},110000,false,30,true,false},{103,PropertyType::StandaloneGarage,{36000,0,21000},240000,false,50,true,false}};}
bool PropertySystem::isResidential(PropertyType t)const{return t!=PropertyType::StandaloneGarage;}
int PropertySystem::ownedResidentialCount()const{int n=0;for(const auto&p:properties)if(p.owned&&isResidential(p.type))++n;return n;}
int PropertySystem::ownedStandaloneGarageCount()const{int n=0;for(const auto&p:properties)if(p.owned&&p.type==PropertyType::StandaloneGarage)++n;return n;}
bool PropertySystem::buy(uint32_t id,int&money){for(auto&p:properties)if(p.id==id&&!p.owned&&money>=p.price){if(isResidential(p.type)&&ownedResidentialCount()>=6)return false;money-=p.price;p.owned=true;if(isResidential(p.type)&&ownedResidentialCount()==1)p.mainResidence=true;return true;}return false;}
bool PropertySystem::setMainResidence(uint32_t id){Property*found=nullptr;for(auto&p:properties)if(p.id==id&&p.owned&&isResidential(p.type))found=&p;if(!found)return false;for(auto&p:properties)p.mainResidence=false;found->mainResidence=true;return true;}
bool PropertySystem::upgradeGarage(uint32_t id,uint8_t slots,int&money,int price){if(slots<1||slots>50||price<0||money<price)return false;for(auto&p:properties)if(p.id==id&&p.owned&&slots>p.garageSlots){money-=price;p.garageSlots=slots;return true;}return false;}
bool PropertySystem::save(const std::string&path)const{FILE*f=std::fopen(path.c_str(),"wb");if(!f)return false;std::fwrite("CLPROP2",1,7,f);for(const auto&p:properties){uint8_t o=p.owned?1:0,m=p.mainResidence?1:0;std::fwrite(&p.id,4,1,f);std::fwrite(&o,1,1,f);std::fwrite(&p.garageSlots,1,1,f);std::fwrite(&m,1,1,f);}std::fclose(f);return true;}
bool PropertySystem::load(const std::string&path){FILE*f=std::fopen(path.c_str(),"rb");if(!f)return false;char h[7];if(std::fread(h,1,7,f)!=7){std::fclose(f);return false;}uint32_t id;uint8_t o,s,m;while(std::fread(&id,4,1,f)==1&&std::fread(&o,1,1,f)==1&&std::fread(&s,1,1,f)==1&&std::fread(&m,1,1,f)==1)for(auto&p:properties)if(p.id==id){p.owned=o!=0;p.garageSlots=s;p.mainResidence=m!=0;}std::fclose(f);return true;}
