#include "game/StoryGameplay.h"
#include "game/GunStoreSystem.h"
#include "game/WildlifeSystem.h"
#include "game/TrophySystem.h"
#include "game/CombatSystem.h"
#include "game/VitaStoryPolish.h"
#include <cstdio>
int main(){
 bool ok=true; StoryGameplay s; ok&=s.startMission1(); ok&=s.reachRhys();ok&=s.enterRhysVehicle();ok&=s.reachDowntown();ok&=s.reachWestSuburbs();ok&=s.reachEastCoast();ok&=s.reachNorthCountryside();ok&=s.reachMountRidge();ok&=s.reachNightCity();ok&=s.completeTour();
 ok&=s.startMission2();ok&=s.reachOldGarage();ok&=s.enterDeliveryCar();ok&=s.deliverCar();ok&=s.loseRivalGang();ok&=s.reachOldWorkshop();ok&=s.completeMission2();
 ok&=s.startMission3();ok&=s.reachHarborDocks();ok&=s.locateElectronicsContainer();ok&=s.enterContainerTruck();ok&=s.loseHarborRivals();ok&=s.deliverElectronics();
 ok&=s.startMission4();ok&=s.escapeIndustrialZone();ok&=s.reachHighway();ok&=s.enterMountainTunnels();ok&=s.survivePolicePursuit();ok&=s.reachNorthCountrysideGarage();
 ok&=s.startMission5(); ok&=s.meetMayjaAtHeistRoom(); ok&=s.chooseGetawayVehicle("dash_getaway_01",true,true,false); ok&=s.collectHeistEquipment(); ok&=s.chooseHeistEscapeRoute(EscapeRoute::Tunnels); ok&=s.reachArmoredTransport(); ok&=s.takeArmoredTransportScore(); ok&=s.enterHeistGetawayVehicle(); ok&=s.escapeFirstHeist(); ok&=s.deliverFirstScore(); ok&=s.mission5Complete();
 ok&=s.startMission6(); ok&=s.meetMayjaAfterFirstScore(); ok&=s.reviewNextJobWithoutRhys(); ok&=s.findRhysNearRivalDistrict(); ok&=s.observeRhysFromDistance(); ok&=s.followRhysOptional(); ok&=s.reportSuspicionToMayja(); ok&=s.mission6Complete();
 ok&=s.startMission7(); ok&=s.meetRhysForIndustrialJob(); ok&=s.enterIndustrialJobSite(); ok&=s.discoverRivalAmbush(); ok&=s.rivalAmbushActive(); ok&=s.surviveRivalAmbush(); ok&=s.rhysSavesDash(); ok&=s.rhysRescueTriggered(); ok&=s.escapeIndustrialAmbush(); ok&=s.debriefMayjaAfterAmbush(); ok&=s.mission7Complete(); ok&=s.insiderConfirmed();
 ok&=s.startMission8(); ok&=s.meetMayjaForSurveillance(); ok&=s.tailRhysUndetected(); ok&=s.captureRhysMeetingEvidence(); ok&=s.rhysMeetingConfirmed(); ok&=s.betrayalEvidenceSecured(); ok&=s.leaveRivalMeetingArea(); ok&=s.showRhysEvidenceToMayja(); ok&=s.mission8Complete();
 ok&=s.startMission9(); ok&=s.briefFakeHeistTrap(); ok&=s.plantFakeHeistInformation(); ok&=s.observeRivalsTakeTheBait(); ok&=s.rhysBetrayalConfirmed(); ok&=s.confrontRhys(); ok&=s.hearRhysConfession(); ok&=s.learnAboutBiggerPlayer(); ok&=s.mission9Complete(); ok&=s.biggerPlayerRevealed();
 ok&=s.startMission10(); ok&=s.traceIndustrialPayment(); ok&=s.recoverPaymentRecord(); ok&=s.followCourierDowntown(); ok&=s.trackTransferToAirport(); ok&=s.followMoneyToWestCoast(); ok&=s.identifyProjectSight(); ok&=s.mission10Complete(); ok&=s.vosslerHoldingsIdentified(); ok&=s.projectSightDiscovered();
 ok&=s.startMission11(); ok&=s.reachHiddenFacility(); ok&=s.infiltrateFacility(); ok&=s.facilityInfiltrated(); ok&=s.reachProjectSightOperationsRoom(); ok&=s.downloadProjectSightTargetMaps(); ok&=s.projectSightArchiveSecured(); ok&=s.recoverCrewDossiers(); ok&=s.identifyAdrianVossler(); ok&=s.adrianVosslerNamed(); ok&=s.escapeFacilityWithArchive(); ok&=s.mission11Complete();
 ok&=s.startMission12(); ok&=s.reviewPhaseIICountdown(); ok&=s.disruptPowerGrid(); ok&=s.disruptTransportNetwork(); ok&=s.phaseIITargetsCompleted()==2; ok&=s.returnToDowntownLockdown(); ok&=s.phaseIILockdownActive(); ok&=s.identifyEliasKane(); ok&=s.eliasKaneIdentified(); ok&=s.surviveVosslerLockdown(); ok&=s.mission12Complete();
 ok&=s.startMission13(); ok&=s.trackEliasKane(); ok&=s.reachKaneSecurityConvoy(); ok&=s.disableKaneEscort(); ok&=s.captureKaneAlive(); ok&=s.kaneCapturedAlive(); ok&=s.interrogateKane(); ok&=s.learnRhysProjectSightHistory(); ok&=s.rhysProjectSightHistoryRevealed(); ok&=s.vosslerIslandDataCenterKnown(); ok&=s.escapeWithKaneIntel(); ok&=s.mission13Complete();
 ok&=s.startMission14(); ok&=s.returnToCrewSafehouse(); ok&=s.safehouseUnderAttack(); ok&=s.surviveSafehouseAssault(); ok&=s.enterCrewEscapeVehicle(); ok&=s.surviveRollingGunfight(); ok&=s.policeHelicopterActive(); ok&=s.evadePoliceHelicopter(); ok&=!s.policeHelicopterActive(); ok&=s.reachOldHideout(); ok&=s.mission14Complete();
 ok&=s.startMission15(); ok&=s.reachDowntownConstructionHotel(); ok&=s.chooseHotelEntryRoute("Service Entrance"); ok&=s.rescueCapturedCrewMember(); ok&=s.hostageRescued(); ok&=s.protectHostage(); ok&=s.escapeParkingGarage(); ok&=s.recoverCleanupIntel(); ok&=s.cleanupRevealed(); ok&=s.mission15Complete();
 ok&=s.startMission16(); ok&=s.meetMayjaForCleanup(); ok&=s.chooseCleanupTarget("Bank Archive"); ok&=s.cleanupChoiceLocked(); ok&=s.neutralizeCleanupTarget(); ok&=s.escapeCleanupRetaliation(); ok&=s.recoverMasterLedger(); ok&=s.masterLedgerRecovered(); ok&=s.centralReserveRevealed(); ok&=s.mission16Complete();
 ok&=s.startMission17(); ok&=s.meetMayjaForLedger(); ok&=s.raidSouthHillsLedgerNode(); ok&=s.raidHarborPortLedgerNode(); ok&=s.traceDowntownMoneyTrail(); ok&=s.raidAirportLedgerNode(); ok&=s.ledgerTargetsCompleted()==4; ok&=s.harborPortLedgerDone(); ok&=s.airportLedgerDone(); ok&=s.southHillsLedgerDone(); ok&=s.downtownMoneyTrailDone(); ok&=s.deliverCompleteLedgerPackage(); ok&=s.mission17Complete();
 ok&=s.startMission18(); ok&=s.meetMayjaForBlackout(); ok&=s.chooseBlackoutOperation("PROTECT THE CREW"); ok&=s.blackoutChoiceLocked(); ok&=s.crewProtectionBonus(); ok&=s.executeBlackoutOperation(); ok&=s.blackoutOperationComplete(); ok&=s.escapeBlackoutResponse(); ok&=s.confirmCentralReserveWindow(); ok&=s.mission18Complete();
 ok&=s.startMission19(); ok&=s.meetMayjaForCentralReserve(); ok&=s.chooseCentralReserveApproach("Underground"); ok&=s.completeWeaponsSetup(); ok&=s.completeGetawayVehiclesSetup(); ok&=s.completeAmmoSetup(); ok&=s.centralReserveReady(); ok&=s.confirmCentralReserveHeist(); ok&=s.centralReserveHeistStarted(); ok&=s.breachCentralReserve(); ok&=s.centralReserveGrossScore()==900000000LL; ok&=s.escapeCentralReserve(); ok&=s.deliverCentralReserveScore(); ok&=s.mission19Complete();
 ok&=s.startCentralReserveAftermath(); ok&=s.survivePostHeistResponse(); ok&=s.secureCentralReserveMoney(); ok&=s.allocateCentralReserveCrewCuts(); ok&=s.centralReserveCutsAllocated(); ok&=s.dashCentralReserveCut()==360000000LL; ok&=s.mayjaCentralReserveCut()==225000000LL; ok&=s.rhysCentralReserveCut()==180000000LL; ok&=s.crewReserveCut()==135000000LL; ok&=s.receiveVosslerAftermathTaunt(); ok&=s.vosslerAftermathTauntReceived(); ok&=s.regroupAfterCentralReserve(); ok&=s.centralReserveAftermathComplete();
 ok&=s.startFinalBattlePreparation(); ok&=s.gatherFinalAmmo(); ok&=s.gatherFinalWeapons(); ok&=s.gatherFinalCars(); ok&=s.gatherFinalArmor(); ok&=s.gatherFinalHeavyResources(); ok&=s.finalSupplyCount()==5; ok&=s.reviewFinalSuppliesBoard(); ok&=s.confirmTakeSightCityReady(true); ok&=s.finalBattlePreparationComplete(); ok&=s.takeSightCityUnlocked();
 ok&=s.startTakeSightCity(); ok&=s.captureFinalTerritory("Harbor"); ok&=s.captureFinalTerritory("Industrial Zone"); ok&=s.captureFinalTerritory("Airport"); ok&=s.captureFinalTerritory("West Suburbs"); ok&=s.captureFinalTerritory("East Suburbs"); ok&=s.finalTerritoriesCaptured()==5; ok&=s.downtownFinalUnlocked(); ok&=s.breachDowntown(); ok&=s.defeatVosslerForces(); ok&=s.chaseVossler(); ok&=s.defeatAdrianVossler(); ok&=s.vosslerDefeated(); ok&=s.finishTakeSightCity(); ok&=s.takeSightCityComplete(); ok&=s.storyComplete();
 ok&=s.startCredits(); ok&=s.creditsStarted(); ok&=s.finishCredits(); ok&=s.creditsFinished(); ok&=s.beginFewWeeksLater(); ok&=s.fewWeeksLaterShown(); ok&=s.enterPostStoryFreeRoam(); ok&=s.postStoryFreeRoam(); ok&=s.vosslerPermanentlyGone(); ok&=s.dynamicGangActivityEnabled(); ok&=s.territoryAttacksEnabled(); ok&=s.survivingCrewCallable(); ok&=s.mayjaSmallHeistsEnabled();
 VitaStoryPolish polish; polish.captureCheckpoint("post_story_free_roam", 0, 0, 900000000LL, 0); StoryCheckpoint restored; ok&=polish.canRetry(); ok&=polish.retryFromCheckpoint(restored); ok&=polish.validateSaveState(s.storyComplete(),s.vosslerPermanentlyGone(),s.postStoryFreeRoam()); ok&=!polish.onlineAllowed(); ok&=polish.hardwareTestRequiredBeforeOnline(); ok&=polish.budget().targetFps==30; ok&=polish.budget().maxWildlife==12; std::printf("Sight City: Underworld M61 OK=%d StoryComplete=%d FreeRoam=%d Checkpoint=%d Vita30FPS=%d WildlifeCap=%d Online=PAUSED HardwareTestRequired=%d\n",ok?1:0,s.storyComplete()?1:0,s.postStoryFreeRoam()?1:0,restored.valid?1:0,polish.budget().targetFps,polish.budget().maxWildlife,polish.hardwareTestRequiredBeforeOnline()?1:0); return ok?0:1;
}
